export const BASE_TYPOGRAPHY_VARIANTS = {
    H1:'h1',
    H2: 'h2',
    H3: 'h3',
    H4: 'h4',
    H5: 'h5',
    H6: 'h6',
    CAPTION: 'caption',
    BODY1: 'body1',
    BODY2: 'body2',
    SUBTITLE1: 'subtitle1',
    SUBTITLE2: 'subtitle2',
    CONTROL_XLARGE: 'controlXLarge',
    CONTROL_LARGE: 'controlLarge',
    CONTROL_MEDIUM: 'controlMedium',
    CONTROL_SMALL: 'controlSmall',
    CONTROL_XSMALL: 'controlXSmall',
} as const